# Generated by Django 5.1.4 on 2025-01-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
